[package]
name = "bogo_shim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.20.0"
bertie = { path = "../" }
rand = "0.8.5"
tracing = "*"
tracing-subscriber = "*"
