(* File automatically generated by Hacspec *)
Set Warnings "-notation-overridden,-ambiguous-paths".
From Crypt Require Import choice_type Package Prelude.
Import PackageNotation.
From extructures Require Import ord fset.
From mathcomp Require Import word_ssrZ word.
(* From Jasmin Require Import word. *)

From Coq Require Import ZArith.
From Coq Require Import Strings.String.
Import List.ListNotations.
Open Scope list_scope.
Open Scope Z_scope.
Open Scope bool_scope.

From Hacspec Require Import ChoiceEquality.
From Hacspec Require Import LocationUtility.
From Hacspec Require Import Hacspec_Lib_Comparable.
From Hacspec Require Import Hacspec_Lib_Pre.
From Hacspec Require Import Hacspec_Lib.

Open Scope hacspec_scope.
Import choice.Choice.Exports.

(* From RecordUpdate Require Import RecordUpdate. *)

(* Import RecordSetNotations. *)

Obligation Tactic := (* try timeout 8 *) solve_ssprove_obligations.

Equations v_LABEL_TLS13 : both (nseq int8 6) :=
  v_LABEL_TLS13  :=
    array_from_list [ret_both (116 : int8);
      ret_both (108 : int8);
      ret_both (115 : int8);
      ret_both (49 : int8);
      ret_both (51 : int8);
      ret_both (32 : int8)] : both (nseq int8 6).
Fail Next Obligation.
