name: hax

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

  schedule:
    - cron: '0 0 * * *'

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  hax:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4
      - uses: hacspec/hax-actions@main
        with: 
          fstar: v2026.03.24
          hax_reference: hax-lib-v0.4.2

      - uses: actions/checkout@v4
        with:
          repository: hacspec/hax
          ref: hax-lib-v0.4.2
          path: hax

      - name: Update dependencies
        run: cargo update

      - name: 🏃🏻‍♀️ Run hax extraction
        run: |
          eval $(opam env)
          ./hax-driver.py extract-fstar

      - name: 🏃🏻‍♀️ Typecheck F* extraction
        env:
          HAX_HOME: ${{ github.workspace }}/hax
        run: ./hax-driver.py typecheck
