name: Nix

on:
  push:
    branches: [main]
  pull_request:

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          source-tag: v0.32.3 # revert when https://github.com/DeterminateSystems/nix-installer-action/issues/133 is closed
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Install & configure Cachix
        shell: bash
        run: |
          nix-env --quiet -j8 -iA cachix -f https://cachix.org/api/v1/install
          cachix use hax
      - uses: actions/checkout@v4
      - run: nix build -L
